package net.purelic.commons.profile;

public enum Preference {

    ARMOR_COLOR,
    ARMOR_COLOR_UNLOCK,
    DEATH_EFFECT,
    FLAG_PATTERN,
    HOTBAR_AXE,
    HOTBAR_AXE_BW,
    HOTBAR_AXE_UHC,
    HOTBAR_BOW,
    HOTBAR_BOW_BW,
    HOTBAR_BOW_UHC,
    HOTBAR_PICKAXE,
    HOTBAR_PICKAXE_BW,
    HOTBAR_PICKAXE_UHC,
    HOTBAR_SHEARS,
    HOTBAR_SHEARS_BW,
    HOTBAR_SHEARS_UHC,
    HOTBAR_SWORD,
    HOTBAR_SWORD_BW,
    HOTBAR_SWORD_UHC,
    HOTBAR_WOOL,
    HOTBAR_WOOL_BW,
    HOTBAR_WOOL_UHC,
    LOBBY,

}
