name: "deploy"

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup java and maven settings
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASS
          gpg-private-key: ${{ secrets.GPG_PRIVATE }}
          gpg-passphrase: GPG_PASS
      - name: setup maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: deploy to ossrh/maven central
        run: mvn clean deploy
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASS: ${{ secrets.OSSRH_PASS }}
          GPG_PASS: ${{ secrets.GPG_PASS }}
